# Generated by Django 5.2.1 on 2026-03-02 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.SlugField(help_text="URL-safe agent identifier", max_length=255)),
                ("display_name", models.CharField(help_text="Human-readable name", max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("claude", "Claude Code"), ("coderoo", "Coderoo")],
                        help_text="Agent platform",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Agent description")),
                (
                    "model",
                    models.CharField(
                        choices=[("sonnet", "Sonnet"), ("opus", "Opus"), ("haiku", "Haiku")],
                        default="sonnet",
                        help_text="AI model",
                        max_length=20,
                    ),
                ),
                ("frontmatter", models.TextField(blank=True, help_text="Raw YAML frontmatter")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this agent is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this agent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["user", "source"], name="agent_build_user_id_41ea4d_idx"),
                    models.Index(fields=["user", "name"], name="agent_build_user_id_a5f350_idx"),
                ],
                "unique_together": {("user", "name")},
            },
        ),
    ]
