# Generated by Django 5.2.1 on 2026-03-02 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title (unnamed chunks hidden from library)",
                        max_length=255,
                    ),
                ),
                ("content", models.TextField(help_text="Markdown content")),
                (
                    "in_library",
                    models.BooleanField(
                        default=False, help_text="Whether this chunk appears in the library"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this chunk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="AgentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(help_text="Order position within the agent"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, help_text="Whether this chunk is active"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_chunks",
                        to="agent_builder.agent",
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_chunks",
                        to="agent_builder.chunk",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="chunks",
            field=models.ManyToManyField(
                blank=True, through="agent_builder.AgentChunk", to="agent_builder.chunk"
            ),
        ),
        migrations.CreateModel(
            name="ChunkVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Variant label (e.g., gentle, firm)", max_length=100
                    ),
                ),
                ("content", models.TextField(help_text="Variant content")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="agent_builder.chunk",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="agentchunk",
            name="active_variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected variant (Phase 3, nullable for now)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agent_builder.chunkvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentchunk",
            unique_together={("agent", "chunk")},
        ),
    ]
