# Generated by Django 5.2.1 on 2026-03-02 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0002_chunk_agentchunk_agent_chunks_chunkvariant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.SlugField(help_text="URL-safe instruction identifier", max_length=255),
                ),
                ("display_name", models.CharField(help_text="Human-readable name", max_length=255)),
                ("content", models.TextField(help_text="Instruction content (Markdown)")),
                (
                    "injection_mode",
                    models.CharField(
                        choices=[("on_demand", "On Demand"), ("auto_inject", "Auto Inject")],
                        default="on_demand",
                        help_text="Default injection mode for this instruction",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this instruction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "injection_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Use Default"),
                            ("on_demand", "On Demand"),
                            ("auto_inject", "Auto Inject"),
                        ],
                        default="",
                        help_text="Override injection mode (blank = use instruction default)",
                        max_length=20,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_instructions",
                        to="agent_builder.agent",
                    ),
                ),
                (
                    "instruction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_instructions",
                        to="agent_builder.instruction",
                    ),
                ),
            ],
            options={
                "ordering": ["instruction__name"],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="instructions",
            field=models.ManyToManyField(
                blank=True, through="agent_builder.AgentInstruction", to="agent_builder.instruction"
            ),
        ),
        migrations.AddIndex(
            model_name="instruction",
            index=models.Index(fields=["user", "name"], name="agent_build_user_id_30905c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="instruction",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="agentinstruction",
            unique_together={("agent", "instruction")},
        ),
    ]
