# Generated by Django 5.2.1 on 2026-03-02 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0003_instruction_agentinstruction_agent_instructions_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_snapshot",
                    models.JSONField(help_text="Snapshot of content fields at this revision"),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, help_text="Optional revision message", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this revision",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="agent_build_content_9132ac_idx"
                    )
                ],
            },
        ),
    ]
