# Generated by Django 5.2.1 on 2026-03-02 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0004_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.SlugField(help_text="Profile identifier", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Profile description")),
                ("snapshot", models.JSONField(help_text="Full system state snapshot")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["user", "name"], name="agent_build_user_id_ff9fbc_idx")
                ],
                "unique_together": {("user", "name")},
            },
        ),
    ]
