# Generated by Django 5.2.1 on 2026-03-02 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0005_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Filename (e.g., CLAUDE.md)", max_length=255),
                ),
                ("path", models.CharField(help_text="Absolute filesystem path", max_length=1024)),
                ("content", models.TextField(blank=True, help_text="File content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this config file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "indexes": [
                    models.Index(fields=["user", "path"], name="agent_build_user_id_b760f8_idx")
                ],
                "unique_together": {("user", "path")},
            },
        ),
    ]
