# Generated by Django 5.2.1 on 2026-03-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0006_configfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="config",
            field=models.TextField(
                blank=True, default="", help_text="Agent config (JSON5 for Coderoo agents)"
            ),
        ),
    ]
