# Generated by Django 5.2.1 on 2026-03-02 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0007_agent_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Project name (derived from directory)", max_length=255
                    ),
                ),
                ("path", models.CharField(help_text="Absolute filesystem path", max_length=1024)),
                (
                    "has_coderoo",
                    models.BooleanField(default=False, help_text="Has .coderoo/ directory"),
                ),
                (
                    "has_claude_config",
                    models.BooleanField(
                        default=False, help_text="Has entry in ~/.claude/projects/"
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(auto_now_add=True, help_text="When first discovered"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["user", "path"], name="agent_build_user_id_145af7_idx"),
                    models.Index(fields=["user", "name"], name="agent_build_user_id_e738cc_idx"),
                ],
                "unique_together": {("user", "path")},
            },
        ),
    ]
