# Generated by Django 5.2.1 on 2026-03-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0008_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="file_mtime",
            field=models.DateTimeField(
                blank=True,
                help_text="Last-seen filesystem modified time at import/apply",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, help_text="When this item was last imported or applied", null=True
            ),
        ),
        migrations.AddField(
            model_name="configfile",
            name="file_mtime",
            field=models.DateTimeField(
                blank=True,
                help_text="Last-seen filesystem modified time at import/apply",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="configfile",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, help_text="When this item was last imported or applied", null=True
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="file_mtime",
            field=models.DateTimeField(
                blank=True,
                help_text="Last-seen filesystem modified time at import/apply",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, help_text="When this item was last imported or applied", null=True
            ),
        ),
    ]
