# Generated by Django 5.2.9 on 2026-03-04 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0009_add_file_mtime_and_last_synced_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "active_tab",
                    models.CharField(
                        choices=[
                            ("agents", "Agents"),
                            ("projects", "Projects"),
                            ("memory", "Memory"),
                        ],
                        default="agents",
                        help_text="Last selected top-level sidebar tab",
                        max_length=20,
                    ),
                ),
                (
                    "agent_sub_tab",
                    models.CharField(
                        choices=[("coderoo", "Coderoo"), ("claude", "Claude")],
                        default="coderoo",
                        help_text="Last selected agent sub-tab",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_builder_options",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "user options",
            },
        ),
    ]
