# Generated by Django 5.2.9 on 2026-03-04 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0010_useroptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agent",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="configfile",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="instruction",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="agent",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="When soft-deleted", null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft-deleted flag"),
        ),
        migrations.AddField(
            model_name="configfile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="When soft-deleted", null=True),
        ),
        migrations.AddField(
            model_name="configfile",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft-deleted flag"),
        ),
        migrations.AddField(
            model_name="instruction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="When soft-deleted", null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft-deleted flag"),
        ),
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="When soft-deleted", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft-deleted flag"),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "name"),
                name="unique_active_agent_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="configfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "path"),
                name="unique_active_configfile_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="instruction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "name"),
                name="unique_active_instruction_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "path"),
                name="unique_active_project_per_user",
            ),
        ),
    ]
