# Generated by Django 5.2.9 on 2026-03-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_builder", "0011_alter_agent_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useroptions",
            name="last_simulate_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Last used project path in simulate modal",
                max_length=1024,
            ),
        ),
    ]
